### ISSUE TITLE
Contain height of modal to the viewport

### ISSUE THREAD

**Issue by lxpocampoFrost** [frost-jm/dev_forum#13]
Contain height of modal to the viewport 

![image](https://github.com/frost-jm/dev_forum/assets/117623161/aed0916d-bfea-429d-85b0-72471a6ebfc7)

Modal is scrollable when content extends, but add some space here 

![image](https://github.com/frost-jm/dev_forum/assets/117623161/f01d20bd-793b-46bf-8df4-46c493bff3ff)

_Originally posted by @lxpocampoFrost in https://github.com/frost-jm/dev_forum/issues/10#issuecomment-1907151483_

**Comment by frost-jm** [comment]
Fixed

**Comment by lxpocampoFrost** [comment]
Modal fixed
